### ISSUE TITLE
Export audio not working

### ISSUE THREAD

**Issue by SreerajVS** [iTCf/TAAC#1]
the export.wav option is not working. It is throwing an error:
"
'wgn' requires Communications Toolbox.

Error in TAAC>ButtonSaveAudioWav_Callback (line 1328)
TmpWhiteNoise=wgn(1,WhiteNoiseLenght,1);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in TAAC (line 115)
    gui_mainfcn(gui_State, varargin{:});

Error in matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)TAAC('ButtonSaveAudioWav_Callback',hObject,eventdata,guidata(hObject))
 
Error while evaluating UIControl Callback."

Can you please fix it?
Regards,
Sreeraj

**Comment by ezemikulan** [comment]
Hi @SreerajVS , it looks like you need to have Matlab's Communications Toolbox installed, however I'll let @SimoneRusso follow up on this.

Best,

**Comment by SimoneRusso** [comment]
Hi @SreerajVS, I confirm what @ezemikulan was saying. You need to have the Matlab's Communications Toolbox (from Mathworks) installed to run several functions of TAAC.

**Comment by SreerajVS** [comment]
Thank you @ezemikulan and @SimoneRusso, it worked well on installing Communications Toolbox.

**Comment by SreerajVS** [comment]
Hi.
Yes it worked and thank you very much.
Apologies for forgetting to update earlier.
Regards,
